### PR TITLE
[Panel User] Add restart and manage_user permissions

### LINKED ISSUE #3304: Panel Users: Users with Full Access do not have "Restart" option in Tools sidebar
PhantomBot Version: 3.9.0.2
O/S Version: Docker/ubuntu
Java Version: Included
Web Browser Version (if Panel related): Firefox 115.0.1

Detailed Description:
In the description for #3227 it is stated that users with "Full Access" will have the Restart button for the bot available in their sidebar, but on creating new users and logging in, this control is not available.

Steps to Reproduce:
Create a new user, check the "Full Access" checkbox to assign all 18 permissions on creation. Log in as new user, set pw, etc and then once fully logged in, inspect sidebar

Logs: Not sure if this would be applicable. Please let me know if you need to me capture something

Screenshots (if applicable):

Missing "Restart" button from Tools sidebar

### PR DESCRIPTION
**Pull request by Sartharon**
Adds checkboxes which enable bot owners to allow panel users to:
- Restart the bot (via the panel) [closes #3304]
- Mange other panel users

Reverts some changes from the [GH-login hotfix](https://github.com/PhantomBot/PhantomBot/pull/3300/commits/c17f932b178657ebf0b04341f21c02bddd0d7f66) due to the config user generating a random token even though `webauth` is already the config user's token. No infinite recursion can occur anymore. Login has been tested locally and on the remote panel for the config user and database users

### CODE REVIEW

File: resources/web/panel/js/pages/global.js [hunk 1]
```diff
@@ -107,7 +107,9 @@ $(function () {
         }
     });
 
-    socket.wsEvent('restart-bot-check', 'RestartRunner', '', [], function (e) {});
+    if (!helpers.currentPanelUserData.canRestartBot) {
```
Comment (gmt2001) [inline resources/web/panel/js/pages/global.js]: Negate?

**Review by gmt2001 — CHANGES_REQUESTED** [review]

**Review by gmt2001 — APPROVED** [review]

**Comment by fouram** [comment]
Hey, this is awesome thank you very much!
