### PR TITLE
Permissions-System Rework

### LINKED ISSUE #2654: [Bug] All Users in permissionstab are VIPs instead of Regulars
PhantomBot Version: 3.5.0.10
Web Browser Version (if Panel related): 1.5.1

Detailed Description:
All users are shown as VIPs.
But with chat command "!permission username" the right permission is shown (f.ex. subscriber)

Screenshots (if applicable):
image
image

### LINKED ISSUE #2657: Custom Command Permissions not honored when swapped
PhantomBot Version: 3.5.0.11
O/S Version: Windows 11
Java Version: Java 11
Web Browser Version (if Panel related):

Detailed Description:
Custom commands permissions are reversed when isSwappedSubscriberVIP is enabled

Steps to Reproduce:
1. Create a custom command via UI and set it to VIP
2. set a user to VIP
3. execute !swapsubscribervip to set it not on default
4. try to use command as user with VIP (no sub)
5. Command will not execute

Logs:

Screenshots (if applicable):

### PR DESCRIPTION
**Pull request by Sartharon**
- Permissions-System Rework/Cleanup and closes #2657, resolves #2654

**Highlights:**
- Unified permission checker `$.checkUserPermission(username, tags, permission)` (tags can be undefined or null)
- Unified role checker:
 `$.isCaster(username)`
 `$.isAdmin(username)`
 `$.isMod(username, tags)` (tags can be undefined or null)
 `$.isSub(username, tags ` (tags can be undefined or null)
 `$.isDonator(username)`
 `$.isVIP(username, tags)` (tags can be undefined or null)
 `$.isRegular(username)`
- Consistent group-ID via "sort-of" enum `$.PERMISSION` always holding the correct permission IDs/levels for each group
image
- Transparently reflected permission level/ID throughout the panel
image
- Simplified or non-existing `isSwappedSubscriberVIP` logic

Deprecated exported functions and their replacements, if any:
- `$.isSwappedSubscriberVIP` REMOVED
- `$.getSubscriberGroupID` replaced by `$.PERMISSIONS.Sub`
- `$.getVIPGroupID` replaced by `$.PERMISSIONS.VIP`
- `$.isSubv3` replaced by `$.isSub(username, tags)`
- `$.isModv3` replaced by `$.isMod(username, tags)`
**Note:** `$.getSubscriberGroupID` and `$.getVIPGroupID` should in most cases be replaced by $.getHighestIDSubVIP and `$.getLowestIDSubVIP` which account for swapped subscriber and VIP IDs (example `$.checkUserPermission(username, tags, $.getHighestIDSubVIP)`)

### CODE REVIEW

File: javascript-source/init.js [hunk 1]
```diff
@@ -520,7 +520,8 @@
             // Check the command permission.
             if ($.permCom(sender, command, subCommand, event.getTags()) !== 0) {
                 $.sayWithTimeout($.whisperPrefix(sender) + $.lang.get('cmd.perm.404', (!$.subCommandExists(command, subCommand) ? $.getCommandGroupName(command) : $.getSubCommandGroupName(command, subCommand))), $.getIniDbBoolean('settings', 'permComMsgEnabled', false));
-                consoleDebug('Command !' + command + ' was not sent due to the user not having permission for it.');
+                //consoleDebug('Command !' + command + ' was not sent due to the user not having permission for it.');
+                $.consoleLn('Command !' + command + ' was not sent due to the user not having permission for it.');
```
Comment (gmt2001) [inline javascript-source/init.js]: Possible debug print

File: resources/web/panel/js/pages/audio/audioHooks.js [hunk 2]
```diff
@@ -389,7 +389,7 @@ $(function() {
             .append(helpers.getDropdownGroup('command-audio', 'Audio Hook', 'Select an Audio Hook', audioNames, 'Audio hook to be played when the command is ran.'))
             // Append a select option for the command permission.
             .append(helpers.getDropdownGroup('command-permission', 'User Level', 'Viewers',
-                ['Caster', 'Administrators', 'Moderators', 'Subscribers', 'Donators', 'VIPs', 'Regulars', 'Viewers'], 'Users who can run the command.'))
+                helpers.getPermGroupNames, 'Users who can run the command.'))
```
Comment (gmt2001) [inline resources/web/panel/js/pages/audio/audioHooks.js]: SyntaxError: Attempt to cast `function` to `array`

File: javascript-source/core/permissions.js [hunk 3]
```diff
@@ -1202,15 +1391,13 @@
...
     $.isMod = isMod;
-    $.isModv3 = isModv3;
     $.isModeratorCache = isModeratorCache;
     $.isOwner = isOwner;
     $.isSub = isSub;
-    $.isSubv3 = isSubv3;
     $.isTurbo = isTurbo;
     $.isDonator = isDonator;
     $.isVIP = isVIP;
-    $.isReg = isReg;
```
Comment (gmt2001) [inline javascript-source/core/permissions.js:1213]: Not a major version release, the global mapping `$.isReg` must be retained for backwards-compatibility and mapped to `isRegular`

File: javascript-source/core/permissions.js [hunk 4]
```diff
@@ -1222,11 +1409,23 @@
...
+    $.getLowestIDSubVIP = getLowestIDSubVIP;
+    $.checkUserPermission = checkUserPermission;
+    $.permCom = permCom;
+
+    //DEPRECATED Functions
     $.isSwappedSubscriberVIP = isSwappedSubscriberVIP;
     $.getSubscriberGroupID = getSubscriberGroupID;
     $.getVIPGroupID = getVIPGroupID;
+    $.isSubv3 = isSubv3;
+    $.isModv3 = isModv3;
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: Function is pass-through to `isMod` with same signature, can change mapping to `$.isModv3 = isMod;`

File: javascript-source/core/permissions.js [hunk 5]
```diff
@@ -1222,11 +1409,23 @@
...
+    $.getHighestIDSubVIP = getHighestIDSubVIP;
+    $.getLowestIDSubVIP = getLowestIDSubVIP;
+    $.checkUserPermission = checkUserPermission;
+    $.permCom = permCom;
+
+    //DEPRECATED Functions
     $.isSwappedSubscriberVIP = isSwappedSubscriberVIP;
     $.getSubscriberGroupID = getSubscriberGroupID;
     $.getVIPGroupID = getVIPGroupID;
+    $.isSubv3 = isSubv3;
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: Function is a pass-through to `isSub` with same signature, can change mapping to `$.isSubv3 = isSub;`

File: javascript-source/core/permissions.js [hunk 6]
```diff
@@ -208,61 +220,89 @@
...
-     * @function isModv3
+     * @function isMod
+     * @deprecated
+     *
      * @export $
      * @param {string} username
      * @param {Object} tags
      * @returns {boolean}
      */
     function isModv3(username, tags) {
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: Function is a pass-through to `isMod` with same signature, can be removed and re-mapped

File: javascript-source/core/permissions.js [hunk 7]
```diff
@@ -208,61 +220,89 @@
...
     /**
      * @function isSubv3
+     * @deprecated
+     *
      * @export $
      * @param {string} username
      * @param {Object} tags
      * @returns {boolean}
      */
     function isSubv3(username, tags) {
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: Function is a pass-through to `isSub` with same signature, can be removed and re-mapped

File: javascript-source/games/adventureSystem.js [hunk 8]
```diff
@@ -526,9 +526,9 @@
      * @event initReady
      */
     $.bind('initReady', function() {
-        $.registerChatCommand('./games/adventureSystem.js', 'adventure', 7);
-        $.registerChatSubcommand('adventure', 'set', 1);
-        $.registerChatSubcommand('adventure', 'top5', 3);
+        $.registerChatCommand('./games/adventureSystem.js', 'adventure', $.PERMISSION.Viewer);
+        $.registerChatSubcommand('adventure', 'set', $.PERMISSION.Admin);
+        $.registerChatSubcommand('adventure', 'top5', $.getHighestIDSubVIP);
```
Comment (gmt2001) [inline javascript-source/games/adventureSystem.js]: SyntaxError: Attempt to cast `function` as `number`

File: javascript-source/core/commandRegister.js [hunk 9]
```diff
@@ -208,18 +208,13 @@
      * @return {Number}
      */
     function getCommandGroup(command) {
-        if (commandExists(command)) {
-            var groupid = commands[command].groupId;
+        var groupid = $.PERMISSION.Viewer;
 
-            if ($.isSwappedSubscriberVIP() && groupid === 3) {
```
Comment (gmt2001) [inline javascript-source/core/commandRegister.js:214]: Permission Error: VIP/Sub permission not maintained when swapped

File: javascript-source/core/panelCommands.js [hunk 10]
```diff
@@ -92,13 +92,10 @@
 
                 if (!$.commandExists(action)) {
                     return;
-                } else if (isNaN(parseInt(group))) {
+                }
+
+                if (isNaN(parseInt(group))) {
                     group = $.getGroupIdByName(group);
-                    if ($.isSwappedSubscriberVIP() && group === 3) {
```
Comment (gmt2001) [inline javascript-source/core/panelCommands.js:97]: Permission Error: VIP/Sub permission not maintained when swapped

File: javascript-source/core/panelCommands.js [hunk 11]
```diff
@@ -125,13 +122,10 @@
 
                 if (!$.subCommandExists(action, subAction)) {
                     return;
-                } else if (isNaN(parseInt(group))) {
+                }
+
+                if (isNaN(parseInt(group))) {
                     group = $.getGroupIdByName(group);
-                    if ($.isSwappedSubscriberVIP() && group === 3) {
```
Comment (gmt2001) [inline javascript-source/core/panelCommands.js:130]: Permission Error: VIP/Sub permission not maintained when swapped

File: javascript-source/core/permissions.js [hunk 12]
```diff
@@ -603,103 +752,141 @@
      * @function generateDefaultGroups
      */
     function generateDefaultGroups() {
-        if (!userGroups[0] || userGroups[0] != 'Caster') {
-            userGroups[0] = 'Caster';
-            $.inidb.set('groups', '0', 'Caster');
+        if (!userGroups[PERMISSION.Caster] || !userGroups[PERMISSION.Caster].equalsIgnoreCase('Caster')) {
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: SyntaxError: Attempt to call unknown function `equalsIgnoreCase` on `string`

File: javascript-source/core/permissions.js [hunk 13]
```diff
@@ -603,103 +752,141 @@
...
+            userGroups[PERMISSION.Caster] = 'Caster';
+            $.setIniDbString('groups', PERMISSION.Caster.toString(), 'Caster');
         }
-        if (!userGroups[1] || userGroups[1] != 'Administrator') {
-            userGroups[1] = 'Administrator';
-            $.inidb.set('groups', '1', 'Administrator');
+        if (!userGroups[PERMISSION.Admin] || !userGroups[PERMISSION.Admin].equalsIgnoreCase('Administrator')) {
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: SyntaxError: Attempt to call unknown function `equalsIgnoreCase` on `string`

File: javascript-source/core/permissions.js [hunk 14]
```diff
@@ -603,103 +752,141 @@
...
+            userGroups[PERMISSION.Admin] = 'Administrator';
+            $.setIniDbString('groups', PERMISSION.Admin.toString(), 'Administrator');
         }
-        if (!userGroups[2] || userGroups[2] != 'Moderator') {
-            userGroups[2] = 'Moderator';
-            $.inidb.set('groups', '2', 'Moderator');
+        if (!userGroups[PERMISSION.Mod] || !userGroups[PERMISSION.Mod].equalsIgnoreCase('Moderator')) {
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: SyntaxError: Attempt to call unknown function `equalsIgnoreCase` on `string`

File: javascript-source/core/permissions.js [hunk 15]
```diff
@@ -603,103 +752,141 @@
...
+            userGroups[PERMISSION.Mod] = 'Moderator';
+            $.setIniDbString('groups', PERMISSION.Mod.toString(), 'Moderator');
         }
-        if (!userGroups[getSubscriberGroupID()] || userGroups[getSubscriberGroupID()] != 'Subscriber') {
-            userGroups[getSubscriberGroupID()] = 'Subscriber';
-            $.inidb.set('groups', getSubscriberGroupID() + '', 'Subscriber');
+        if (!userGroups[PERMISSION.Sub] || !userGroups[PERMISSION.Sub].equalsIgnoreCase('Subscriber')) {
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: SyntaxError: Attempt to call unknown function `equalsIgnoreCase` on `string`

File: javascript-source/core/permissions.js [hunk 16]
```diff
@@ -603,103 +752,141 @@
...
+            userGroups[PERMISSION.Sub] = 'Subscriber';
+            $.setIniDbString('groups', PERMISSION.Sub.toString(), 'Subscriber');
         }
-        if (!userGroups[4] || userGroups[4] != 'Donator') {
-            userGroups[4] = 'Donator';
-            $.inidb.set('groups', '4', 'Donator');
+        if (!userGroups[PERMISSION.Donator] || !userGroups[PERMISSION.Donator].equalsIgnoreCase('Donator')) {
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: SyntaxError: Attempt to call unknown function `equalsIgnoreCase` on `string`

File: javascript-source/core/permissions.js [hunk 17]
```diff
@@ -603,103 +752,141 @@
...
+            userGroups[PERMISSION.Donator] = 'Donator';
+            $.setIniDbString('groups', PERMISSION.Donator.toString(), 'Donator');
         }
-        if (!userGroups[getVIPGroupID()] || userGroups[getVIPGroupID()] != 'VIP') {
-            userGroups[getVIPGroupID()] = 'VIP';
-            $.inidb.set('groups', getVIPGroupID() + '', 'VIP');
+        if (!userGroups[PERMISSION.VIP] || !userGroups[PERMISSION.VIP].equalsIgnoreCase('VIP')) {
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: SyntaxError: Attempt to call unknown function `equalsIgnoreCase` on `string`

File: javascript-source/core/permissions.js [hunk 18]
```diff
@@ -603,103 +752,141 @@
...
+            userGroups[PERMISSION.VIP] = 'VIP';
+            $.setIniDbString('groups', PERMISSION.VIP.toString(), 'VIP');
         }
-        if (!userGroups[6] || userGroups[6] != 'Regular') {
-            userGroups[6] = 'Regular';
-            $.inidb.set('groups', '6', 'Regular');
+        if (!userGroups[PERMISSION.Regular] || !userGroups[PERMISSION.Regular].equalsIgnoreCase('Regular')) {
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: SyntaxError: Attempt to call unknown function `equalsIgnoreCase` on `string`

File: javascript-source/core/permissions.js [hunk 19]
```diff
@@ -603,103 +752,141 @@
...
+            userGroups[PERMISSION.Regular] = 'Regular';
+            $.setIniDbString('groups', PERMISSION.Regular.toString(), 'Regular');
         }
-        if (!userGroups[7] || userGroups[7] != 'Viewer') {
-            userGroups[7] = 'Viewer';
-            $.inidb.set('groups', '7', 'Viewer');
+        if (!userGroups[PERMISSION.Viewer] || !userGroups[PERMISSION.Viewer].equalsIgnoreCase('Viewer')) {
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: SyntaxError: Attempt to call unknown function `equalsIgnoreCase` on `string`

**Review by gmt2001 — CHANGES_REQUESTED** [review]

**Comment by gmt2001** [comment]
Please also check the _Codacy Static Code Analysis_ annotations

File: javascript-source/core/permissions.js (hunk 3 above)
Comment (Sartharon) [reply javascript-source/core/permissions.js:1213]: I was afraid this will be sth that comes up.
The issue I see (same with `isModv3 `and `isSubv3 `as well as the mappings I left intact) is that the functions do not 100% do the same anymore.
The original `isRegular `checked if the user had _Regular_ permissions or any higher permissions, the new `isReg `function just tell is if the user is exactly that and not if  same as the isSubv3 and isModv3 did at that time.

Checking for permissions like `isRegular` was doing should be done with `$.checkUserPermission(username, tags, permission)` for consistency reasons and to reduce duplicate logic and ensuring the permission check works as intended where used.

I'm hesitant to just map `$.isRegular` to `isReg` because of the above-mentioned possibly breaking custom stuff.
I'm leaning towards just getting the old logic back and marking it as deprecated, leaving the new logic in (which is used throughout the modules).

But I'm open for your take on this

Comment (gmt2001) [reply javascript-source/core/permissions.js:1213]: In that case we would make a deprecated function which uses the new logic to achieve the same result until a new major release occurs

File: javascript-source/core/commandRegister.js (hunk 9 above)
Comment (Sartharon) [reply javascript-source/core/commandRegister.js:214]: This is done one in $.PERMISSIONS now
Or am I miss understanding you?

If we swap VIP and Sub perm

VIPs are allowed to run the commands subs were allowed before, and subs cannot run those anymore since their level got lowered.
If i we change the command perm as well, subs would be allowed to still run the command, hence:

Before:
Subs allowed
VIPS not allowed

After:
Subs allowed
VIPs allowed

Thus, not only just swapping VIP and Sub but also changing every single command perm

File: javascript-source/core/panelCommands.js (hunk 10 above)
Comment (Sartharon) [reply javascript-source/core/panelCommands.js:97]: This is done one in $.PERMISSIONS now

File: javascript-source/core/panelCommands.js (hunk 11 above)
Comment (Sartharon) [reply javascript-source/core/panelCommands.js:130]: This is done one in $.PERMISSIONS now

File: javascript-source/core/commandRegister.js (hunk 9 above)
Comment (Sartharon) [reply javascript-source/core/commandRegister.js:214]: Maybe to better clarify on how this works atm:
`!sub` is set to `3` (Sub) permission before swapping
`!vip` is set to `5` (VIP) permission before swapping
image

Before swapping:
image

After swapping:
image

File: javascript-source/core/permissions.js [hunk 20]
```diff
@@ -208,61 +220,64 @@
...
      * @returns {boolean}
      */
-    function isMod(username) {
-        return isModeratorCache(username.toLowerCase()) || getUserGroupId(username.toLowerCase()) <= 2 || isOwner(username);
+    function isModNoTags(username) {
+        return isModeratorCache(username.toLowerCase()) || queryDBPermission(username.toLowerCase()) <= PERMISSION.Mod || isOwner(username);
+    }
+
+    function checkTags(tags) {
+        return !(tags === null || tags != '{}' || tags != '-1' || tags === undefined);
```
Comment (gmt2001) [inline javascript-source/core/permissions.js]: Expected '!==' and instead saw '!='

**Review by gmt2001 — CHANGES_REQUESTED** [review]
One last change

**Review by gmt2001 — DISMISSED** [review]

**Review by gmt2001 — APPROVED** [review]
